config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'owner', to: 'pages#owner'
  get 'about', to: 'pages#about'
  get 'missions', to: 'pages#missions'
  get 'dashboard', to: 'pages#dashboard'
  get 'label', to: 'pages#label'

  resources :flats do
    member do
      patch :validate
    end
  end

  resources :simulations, only: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  TYPOLOGY = ["studio", "t1", "t2", "t3", "t4", "t5"]
  CURRENT_STATE = ["libre", "occupe"]
  APPARTEMENT_CONDITION = ["travaux à prevoir", "à rafraîchir", "neuf"]
  ORIGIN_CONTACT = ["delegation secours catholique", "proprietaires actuels agence", "FAPIL", "ANAH", "internet", "presse", "autre"]
   validates :typology, inclusion: { in: TYPOLOGY }
   validates :current_state, inclusion: { in: CURRENT_STATE }
   validates :appartement_condition, inclusion: { in: APPARTEMENT_CONDITION }
   validates :origin_contact, inclusion: { in: ORIGIN_CONTACT }
end

app/models/simulation.rb
class Simulation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flats
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  add_flash_types :danger, :success
  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

    private


  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :ensure_user_is_owner, only: [:index, :new, :create, :destroy]

  def index
    @flats = policy_scope(Flat).order(created_at: :desc)
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat

    if @flat.save
      redirect_to flats_path, success: "Votre annonce a bien été créé"
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    authorize @flat
    if @flat.save
      redirect_to flats_path, success: "L'annonce a bien été mise à jour"
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    authorize @flat

    if current_user
      redirect_to flats_path, danger: "Annonce bien supprimée"
    else
      redirect_to flats_path
    end
  end

  def show
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def validate
    @flat = Flat.find(params[:id])
    authorize @flat

    @flat.update(status: true)
    redirect_to dashboard_path, success: "Logement validé"
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit( :title, :address, :typology, :area, :rent, :rental_charges, :current_state, :appartement_condition, :origin_contact, :message, :photos)
  end

  def ensure_user_is_owner
    return unless current_user.admin?

    user_not_authorized
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :owner, :about, :missions, :label ]

  def home
  end

  def owner
  end

  def about
  end

  def missions
  end

  def label
  end

  def dashboard
    @flats = Flat.all.geocoded

    if params[:filter]
      @flats = @flats.where(typology: params[:filter][:typology])
    end

    authorize current_user
    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flat: flat })
      }
    end
  end

end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_action :skip_authorization
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @simulation = Simulation.new
  end

  def create
    @simulation = Simulation.new(simulation_params)

      if @simulation.save
      redirect_to simulation
    else
      render :new
    end
  end

private

  def simulation_params
    params.require(:simulation).permit(:zone, :area, :percentage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/flats/_form.html.erb
  <div class="add-form container col-sm-8 col-lg-6">
      <%= simple_form_for (@flat) do |f| %>
        <div class="row">
          <div class="col">
            <%= f.input :title, label: "Titre de votre annonce"%>
          </div>
          <div class="col">
            <%= f.input :address, label: "Adresse", id: "flat_address" %>
          </div>
       </div>

        <div class="row">
            <div class="col">
            <%= f.input :typology, collection: Flat::TYPOLOGY,label: "Typologie du bien" %>
          </div>
          <div class="col mt-4">
            <%= f.input :area, label: "Surface*", hint:"*(en m²)" %>
          </div>
          <div class="col mt-4">
            <%= f.input :rent, label: "Prix du loyer" %>
          </div>
          <div class="col">
            <%= f.input :rental_charges, label: "Montant des charges" %>
          </div>
        </div>
        <div class="col">
            <%= f.input :current_state, collection: Flat::CURRENT_STATE, label: "Etat actuel" %>
          </div>
          <div class="col">
            <%= f.input :appartement_condition, collection: Flat::APPARTEMENT_CONDITION, label: "Etat du bien" %>
          </div>
        <div class="col">
            <%= f.input :origin_contact, collection: Flat::ORIGIN_CONTACT, label: "Comment avez vous entendu parler de nous ?" %>
          </div>
          <div class="col">
            <label class="btn btn-outline-info" style="style: width: 100%">
              Ajouter une photo <em> (10.5 Mb max.)</em>
              <span style="display:none;">
                <%= f.input :photos, as: :file, name: 'Photo' %>
              </span>
            </label>
          </div>
          <%= f.input :message, placeholder: "Ecrivez votre message..." %>
          <div class="new-form-buttons">
          <%= f.submit "Proposer", class: "btn submit-new our-button"  %>
        </div>
      <% end %>
  </div>

app/views/flats/edit.html.erb
<div class="box">
  <div class="add-image">
    <h2>MODIFIER MON ANNONCE</h>
  </div>
    <%= render 'flats/form' %>
</div>

app/views/flats/index.html.erb
<div class="container flats">
  <div class="text-center mt-5">
      <h2>MES APPARTEMENTS</h2>
      <hr>
    </div>
  <div class="row">
    <div class="col-xs-6 mx-auto">
      <%= link_to new_flat_path, class: "text-decoration-none" do %>
      <div class="container-fluid add">
        <div class="text-center">
          <img src="https://image.flaticon.com/icons/svg/1828/1828817.svg" alt="" style="width: 30px;"></div>
          <div class="text-center mt-3">Ajouter un nouveau logement</div>
      </div>
      <% end %>
    </div>
  </div>

  <% if danger %>
    <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
      <%= danger %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% elsif success %>
    <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
      <%= success %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

  <div class="row mb-5">
    <% @flats.each do |flat| %>
      <div class="col-xs-4 mt-5 flats">
        <div class="card-flat">
          <% if flat.photos.attached? %>
            <% flat.photos.each do |photo| %>
              <%= cl_image_tag photo.key %>
            <% end %>
          <% else %>
            <%= image_tag "https://image.freepik.com/photos-gratuite/modele-jouet-maison-vue-face-cles-arriere-plan-flou_23-2148301690.jpg" %>
          <% end %>
        <div class="card-flat-infos">
          <h2><%= flat.title %></h2>
          <p><%= flat.address %></p>
          <p><%= flat.area %>m²</p>
          <p><%= flat.typology.upcase %></p>
        </div>
        <div class="container icons">
           <% if flat.status == true %>
            <div class="status-owner"><i class="fas fa-check-circle fa-lg" style="color: #21bf73;"></i></div>
          <% else %>
            <div class="status-owner">🔴</div>
          <% end %>
            <label for="box2" id="sweet-alert-trash-<%=flat.id%>" class="btn btn-flat our-button alt" style="padding: 5px 12px;"><i class="far fa-trash-alt fa-sm"></i></label>
            <%= link_to flat_path(flat), method: :delete, id: "delete-link-#{flat.id}" do %>
            <% end %>

            <%= link_to edit_flat_path(flat), class: 'btn btn-flat our-button mb-2', style:'padding: 5px 12px;' do %>
              <i class="far fa-edit fa-sm"></i>
            <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="box">
  <div class="add-image">
    <h2>PROPOSER VOTRE LOGEMENT</h>
  </div>
    <%= render 'flats/form' %>
</div>

app/views/flats/show.html.erb
<div class="container show">
  <div class="text-center mt-5">
      <h2>LOGEMENT</h2>
    </div>
  <div class="row mt-5">
    <div class="col-6">
      <div class="show-flats">
        <% if @flat.photos.attached? %>
          <% @flat.photos.each do |photo| %>
            <%= cl_image_tag photo.key %>
          <% end %>
          <% else %>
            <%= image_tag "https://image.freepik.com/photos-gratuite/modele-jouet-maison-vue-face-cles-arriere-plan-flou_23-2148301690.jpg" %>
          <% end %>
      </div>
    </div>
      <div class="col-6">
        <h3 class="text-center" style="font-size: 20px;">Proposition de <%= @flat.user.first_name.capitalize %> <%= @flat.user.last_name.capitalize %></h3>
        <ul class="list-group list-group-flush text-center" style="font-size: 17px;">
          <li class="list-group-item"><em><%= @flat.address %></em></li>
          <li class="list-group-item"><em><%= @flat.user.email %></em></li>
          <li class="list-group-item">Le bien est un  <strong style="color: #025D90;"><%= @flat.typology.upcase %></strong></li>
          <li class="list-group-item">La surface est de  <strong style="color: #025D90;"><%= @flat.area %>m²</strong></li>
          <li class="list-group-item">Le loyer actuel est de <strong style="color: #025D90;"><%= @flat.rent %>€</strong></li>
          <li class="list-group-item">Le montant des charges est de <strong style="color: #025D90;"><%= @flat.rental_charges %>€</strong></li>
          <li class="list-group-item">Etat actuel  <strong style="color: #025D90;"><%= @flat.current_state %></strong></li>
          <li class="list-group-item">Etat du bien  <strong style="color: #025D90;"><%= @flat.appartement_condition %></strong></li>
        </ul>
          <div class="container d-flex justify-content-center mt-5">
           <div class="mr-2">
              <%= link_to 'Modifier', edit_flat_path(@flat), class: 'btn btn-flat my-button' %>
           </div>
           <div>
              <% if @flat.status == false %>
                <%= link_to validate_flat_path(@flat), method: :patch, id: "validate-link-#{@flat.id}", class: "text-decoration-none btn btn-validate" do %>
              Valider
              <% end %>
            <% end %>
           </div>
        </div>
      </div>
  </div>
  <div class="link-dashboard mt-3">
    <%= link_to dashboard_path do %>
    <i class="fas fa-chevron-circle-left fa-sm"><span style="margin-left: 8px; font-family: 'Karla';">Retour Tableau de Bord</span></i>
    <% end %>
  </div>
</div>
</div>

app/views/pages/_info_window.html.erb
<h4 class="text-center" style="font-size: 16px; color: #025D90; font-weight: : bold;"><%= flat.user.first_name.capitalize %> <%= flat.user.last_name.capitalize %></h4>
<p><%= flat.address %></p>
<%= link_to "Voir annonce", flat_path(flat), class: "text-decoration-none" %>

app/views/pages/home.html.erb
<div class="row mt-5">
  <div class="col-8 offset-2">
    <div class="banner-home">
        <div class="banner-content">
          <h1>AIS CARITAS IDF</h1>
            <h2><span id="banner-typed-text"></span></h2>
        </div>
      </div>
  </div>
</div>

<div class="container homepage">
  <div class="row">
    <div class="col">
      <h2 class=title-home>L’<strong>Agence Immobilière Sociale CARITAS</strong> a pour vocation d’éveiller un engagement solidaire auprès des propriétaires sensibles aux problématiques de mal-logement. <br/>
      </h2>
      <h3 class=title-home style="font-size: 18px; line-height: 1.4;">La location solidaire repose sur des déductions fiscales, pouvant atteindre <strong>jusqu’à 85 % des revenus locatifs</strong>, pour les propriétaires privés qui acceptent de louer leur logement à un loyer maîtrisé pour des ménages en difficulté.<br/>
        <em>Vous avez la possibilité d'effectuer une estimation de votre rendement locatif.</em></h3>
      <div class="row d-flex justify-content-center mt-3 mb-5">
      <div class="buttons">
        <%= link_to "Simulation", new_simulation_path, class: "btn our-button"  %>
      </div>
    </div>
    </div>
  </div>

  <div class="row card-group">
    <div class="col-xs-6 mx-auto">
      <div class="card home">
        <div class="icon">
          <img src="https://image.flaticon.com/icons/svg/821/821567.svg" alt="">
        </div>
        <div class="contentBx text-center mt-3">
          <h3>Gestion locative de proximité</h3>
            <p>Contribuer à faire une démarche utile et solidaire en louant votre bien à des spécialistes de l'immobilier</p>
            <%= link_to "En Savoir plus", about_path, class: "nav-link" %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 mx-auto">
      <div class="card">
        <div class="icon">
          <img src="https://image.flaticon.com/icons/svg/821/821564.svg" alt="">
        </div>
        <div class="contentBx text-center mt-3">
          <h3>Devenez Propriétaire Solidaire</h3>
            <p>Une gestion locative adaptée qui a pour but de sécuriser la relation locative entre un propriétaire et son locataire</p>
            <%= link_to "En Savoir plus", owner_path, class: "nav-link" %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 mx-auto">
      <div class="card">
        <div class="icon">
          <img src="https://image.flaticon.com/icons/svg/822/822795.svg" alt="">
        </div>
        <div class="contentBx text-center mt-3">
          <h3>Accompagnement des ménages</h3>
            <p>Suivi social, soutien aux démarches administratives, accompagnement sur le budget domestique</p>
            <a href="#"><span>En Savoir plus</span></a>
        </div>
      </div>
    </div>
  </div>
  <div class="variable-width mt-5 carousel" style="margin-bottom: 8%;">
    <div class="card-product">
      <%= image_tag "carousel_1.jpg", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Chloé, <em class="testimonial">Bénévole</em></h4>
        <p>Je m'investis depuis 1 an auprès d'une famille logée à Paris</p>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag "carousel6.jpg", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Famille Martin, <em class="testimonial">Locataire</em></h4>
        <p>Nous sommes enfin heureux et soulagés d'avoir un logement décent</p>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag "caroussel3.jpg", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Jean-Jacques, <em class="testimonial">Propriétaire</em></h4>
        <p>Fiable et de confiance, je ne regrette pas ma démarche de propriétaire solidaire</p>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag "carousel7.jpg", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Marc, <em class="testimonial">Bénévole</em></h4>
        <p>J'accompagne une famille dans la vie par le logement</p>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag "carousel4.png", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Sophie, <em class="testimonial">Propriétaire</em></h4>
        <p>Je n'ai pas hésité un instant et me suis tout de suite engagée à louer mon T2</p>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag "caroussel2.jpg", size: "180x170", crop: "fill" %>
      <div class="card-product-infos">
        <h4>Mireille, <em class="testimonial">Locataire</em></h4>
        <p>Je me sens enfin soutenue dans mes démarches</p>
      </div>
    </div>
  </div>

  </div>
</div>

app/views/pages/missions.html.erb
<div class="container">
  <div class="container-owner">
    <div class="row">
      <div class="col-xs-6 mx-auto">
        <div class="title-missions">
          <h2>NOS MISSIONS</h2>
          <h3>La gestion locative notre priorité</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="banner-missions text-center"></div>

 <div class="content-container">

<h3>Une Gestion de proximité,tranquillité et sérénité de gestion, relation constante avec le locataire et le propriétaire</h3>


<p>L’AIS CARITAS IDF s’engage à sécuriser le rapport locatif par :</p>

Une adaptation du logement aux besoins et ressources du locataire.
Identification des locataires par les délégations franciliennes du Secours Catholique et évaluation des besoins et des possibilités d’engagement du ménage par un travailleur social dédié.
Vérification de sa capacité financière et constitution du dossier de demande de logement (justificatifs d’identité et de revenus etc…)
un entretien du logement et un suive des travaux

roposer un logement décent aux ménages les plus fragiles, un suivi technique qui permet la pérennité de votre logement

accompagnement des ménages
</div>

app/views/pages/owner.html.erb
<div class="container">
  <div class="container-owner">
    <div class="row">
      <div class="col-xs-6 mx-auto">
        <div class="title-owner">
          <h2>DEVENEZ PROPRIETAIRE SOLIDAIRE</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="banner-owner text-center"></div>
  <div class="container">
    <div class="row">
      <div class="col title-owner">
        <h3>Vous êtes propriétaire et souhaitez-vous engager dans un projet solidaire ?</h3>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        <p>L'<strong>Agence Immobilière Sociale Caritas</strong> vous aide à formaliser votre besoin et vous conseille sur les différents cadres locatifs à votre disposition. <br/>
        Elle s'engage à vos côtés, pour vous apporter des réponses adaptées  à vos attentes et à votre projet, tout en s'inscrivant dans une démarche sociale et solidaire. <br/>
        Vous aurez la possibilité en fin de page d'effectuer une <strong><a href="/simulations/new" class="text-decoration-none">simulation</strong></a> sur votre potentiel rendement locatif et proposer votre logement à l'Agence.</p>
      </div>
    </div>
    <div class="row">
      <blockquote class="quote-card text-center">
        <p>La location avec conventionnement de l'<strong>ANAH</strong> comporte de multiples avantages aux bénéfices des propriétaires tels que des primes, des aides aux travaux, ainsi qu'un dégrèvement fiscal du revenu locatif pouvant aller <strong>jusqu'à 85%</strong>.</p>
      </blockquote>
    </div>
    <div class="row">
      <div class="col text-center">
        <h3 class="title-owner">Nos services</h3>
        <p>Une gestion de votre logement assurée par des professionnels de l'immobilier.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>Conseils auprès des propriétaires sur les différents cadres locatifs à leur disposition</p>
            </div>
          </div>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>Sécurisation des risques locatifs : impayés de loyer, dégradations, vacance locative</p>
            </div>
          </div>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>Recherche de locataire parmi les ménages identifiés et étude approfondie des candidatures</p>
            </div>
          </div>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>En cas d'un conventionnement avec l'ANAH : conception du dossier de conventionnement et suivi de celui-ci auprès des organismes référents</p>
            </div>
          </div>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>Visite technique trimestrielle des logements. En cas de travaux, une demande de devis et suivi de chantier est réalisé, grâce au réseau de professionnels agrées</p>
            </div>
          </div>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="card owner">
          <div class="contentBx d-flex justify-content-center">
            <img src="https://image.flaticon.com/icons/svg/1632/1632670.svg" alt="">
            <div class="text ml-4 text-align">
              <p>Rédaction des actes et réalisation des états des lieux. Encaissement des loyer et révision de ceux-ci quand il convient, régularisation des charges locatives</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col title-owner">
        <h3 style="font-size: 18px;">Vous pourrez retouver plus de détails de nos services en prenant également contact avec nous.</h3>
      </div>
    </div>
    <div class="row d-flex justify-content-center mb-5">
      <div class="buttons">
        <%= link_to "Simulation", new_simulation_path, class: "btn our-button"  %>
        <%= link_to "Proposer", new_flat_path, class: "btn our-button"  %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to root_path, class: "navbar-logo" do %>
    <%= image_tag "logo.JPG" %>
  <% end %>
  <input id="hamburger" class="hamburger" type="checkbox"/>
    <label class="hamburger" for="hamburger">
      <i></i>
        <text>
          <close>fermer</close>
          <open>menu</open>
        </text>
    </label>
  <section class="drawer-list">
    <ul class="navbar-nav">
      <% if not user_signed_in? %>
        <li class="nav-item">
          <%= link_to "QUI SOMMES NOUS", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "DEVENEZ PROPRIETAIRE SOLIDAIRE", owner_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "SIMULATION", new_simulation_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "NOS MISSIONS", missions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "LABEL ET PARTENAIRES", label_path, class: "nav-link" %>
        </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
            <i class="fas fa-user-plus"></i> INSCRIPTION
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt"></i> CONNEXION
            <% end %>
          </li>
      <% else %>
          <li class="nav-item">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, width: 65, height: 65, crop: :thumb, gravity: :face, class: "avatar float-right", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://image.flaticon.com/icons/svg/149/149071.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "QUI SOMMES NOUS", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "DEVENEZ PROPRIETAIRE SOLIDAIRE", owner_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "SIMULATION", new_simulation_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "NOS MISSIONS", missions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "LABEL ET PARTENAIRES", label_path, class: "nav-link" %>
          </li>
          <span class="border-bottom" style="width: 85%; margin-left: 56px;"></span>
             <% if current_user.admin %>
             <li class="nav-item">
            <%= link_to "Tableau de bord", dashboard_path , class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Mes appartements", flats_path(@flats) , class: "nav-link" %>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% end %>
            </li>
      <% end %>
    </ul>>
  </section>
</nav>